<script lang="ts">
  import type {Snapshot,Classroom,SeatingDocument,Draft,Candidate} from '../../lib/seating/types';
  import { onMount } from 'svelte';
  import { getCurrentWindow } from '@tauri-apps/api/window';
  import { invoke } from '@tauri-apps/api/core';
  import { listen } from '@tauri-apps/api/event';
  import { X, Minus, Plus, Undo2, Redo2, Download, Eye, Settings2, Armchair, LayoutGrid, Maximize2, BookOpen, CircleHelp, ChevronUp } from 'lucide-svelte';
  import { dragRegion } from '../../lib/dragRegion.js';
  import { openTool } from '../../lib/toolkit/windows.js';
  import { openRosterFor } from '../../lib/classroom/intent.js';
  import { readRoster, subscribeRoster, native, context, watchContext, saveAction } from '../../lib/seating/repository.js';
  import { clone, newDocument, newDraft, publicBoard, makeLayout, resizeLayout, SHAPES, uid, reconcile, dailyArchives } from '../../lib/seating/model.js';
  import { validAssignments, violations } from '../../lib/seating/solver.js';
  import { downloadPng } from '../../lib/seating/export.js';
  import { createSeatingAudio } from '../../lib/seating/audio.js';
  import ClassroomScene from './ClassroomScene.svelte';
  import SeatingGuide from './SeatingGuide.svelte';
  import TeacherPanel from './TeacherPanel.svelte';
  import './seating.css';
  let {teacherOnly=false}: {teacherOnly?:boolean} = $props();
  let snapshot=$state<Snapshot>({revision:0,classes:[],defaultClassId:null}),classroom=$state<Classroom>({id:'',name:'',revision:0,students:[],groups:[]}),doc=$state<SeatingDocument>(newDocument()),draft=$state<Draft>(newDraft()),ready=$state(false),follow=$state(true),pinned=$state('');
  let error=$state(''),status=$state(''),pending=$state(0),failed=$state(false),frozen=$state(false),selected=$state<string[]>([]),chosenStudent=$state(''),teacher=$state(false),zoom=$state(1),simple=$state(false),fontSize=$state(18),modal=$state(''),columns=$state(6),shape=$state('pairs'),numbersOnly=$state(false);
  type RevealEffect='none'|'curtain'|'sequence'|'click';
  let rearrangeMotion=$state(true),revealEffect=$state<RevealEffect>('none'),effectMenuOpen=$state(false),soundEnabled=$state(true),countdown=$state(0),curtainClosed=$state(false),curtainOpening=$state(false),curtainPreparing=$state(false),sequenceActive=$state(false),clickRevealActive=$state(false),revealedCount=$state(0),clickRevealedIds=$state<string[]>([]);
  const seatAudio=createSeatingAudio();
  let undo=$state<Draft[]>([]),redo=$state<Draft[]>([]),candidates=$state<Candidate[]>([]),working=$state(false),resultMessage=$state(''),candidateIndex=$state(-1),worker:Worker|null=null,run=0,queue=Promise.resolve(),disposed=false,loading=0,ownRevision=-1;
  let finalSaveTimer:ReturnType<typeof setTimeout>|null=null,curtainTimer:ReturnType<typeof setTimeout>|null=null,revealTimer:ReturnType<typeof setInterval>|null=null,revealStepTimer:ReturnType<typeof setTimeout>|null=null;
  let helpButton=$state<HTMLButtonElement|undefined>(undefined);
  const board=$derived(draft&&classroom?{...publicBoard(draft,classroom.students,classroom.name),seats:draft.layout.seats.map(s=>{const p=classroom.students.find(p=>p.id===draft.assignments[s.id]);return {...s,name:p?.name||'',number:p?.number||'',appearance:draft.appearances[p?.id||""]||p?.gender||'unspecified',gender:p?.gender||'unspecified'};})}:null);
  const revealIds=$derived(board?.seats.filter(s=>s.name).map(s=>s.id)||[]);
  const revealInProgress=$derived(sequenceActive||clickRevealActive);
  const concealedIds=$derived(clickRevealActive?revealIds.filter(id=>!clickRevealedIds.includes(id)):[]);
  const shownBoard=$derived(board&&revealInProgress?{...board,seats:board.seats.map(s=>!s.name||sequenceActive&&revealIds.indexOf(s.id)<revealedCount||clickRevealActive&&clickRevealedIds.includes(s.id)?s:{...s,name:'',number:'',appearance:'unspecified',gender:'unspecified'})}:board);
  const waiting=$derived(classroom&&draft?classroom.students.filter(p=>!draft.excluded.includes(p.id)&&!Object.values(draft.assignments).includes(p.id)):[]);
  const lockedSeats=$derived(draft.rules.filter(r=>r.kind==='fixed').map(r=>r.seatId).filter((id):id is string=>!!id));

  const current=$derived(doc?.archives.find(a=>a.id===doc.currentId));
  async function refresh(){if(disposed||pending||failed)return;const ticket=++loading;try{const s=await readRoster();if(disposed||ticket!==loading)return;let id;if(teacherOnly){const c=await context();id=c.follow?s.defaultClassId:c.classId;}else id=follow?s.defaultClassId:pinned;
    if(disposed||ticket!==loading||pending||failed)return;snapshot=s;const next=s.classes.find(c=>c.id===id)||null;const incoming=next?(s.seating?.[id||""]||newDocument(next.students.length)):null;
    if(!next){stop();classroom={id:'',name:'',revision:0,students:[],groups:[]};draft=newDraft();doc=newDocument();ready=true;return;}
    const switched=classroom?.id!==id;if(switched){stop();seatAudio.stop();curtainClosed=false;curtainPreparing=false;selected=[];chosenStudent='';undo=[];redo=[];status=classroom?`${next.name}으로 바뀌었어요.`:'';}
    const changed=switched||incoming!.revision!==ownRevision||classroom?.revision!==next.revision;
    classroom=next;doc=incoming!;ownRevision=incoming!.revision;if(changed){stop();seatAudio.stop();curtainPreparing=false;curtainClosed=false;draft=reconcile(incoming!.draft,next);candidates=[];candidateIndex=-1;}
    if(!teacherOnly&&switched)await context(id,follow);ready=true;
  }catch(e){error=String(e);ready=true;}}
  function finishReveal(){if(revealTimer)clearInterval(revealTimer);if(revealStepTimer)clearTimeout(revealStepTimer);revealTimer=null;revealStepTimer=null;sequenceActive=false;clickRevealActive=false;revealedCount=0;clickRevealedIds=[];}
  function startSequence(){finishReveal();if(!revealIds.length)return;selected=[];chosenStudent='';sequenceActive=true;revealedCount=0;revealTimer=setInterval(()=>{revealedCount++;if(revealedCount>=revealIds.length){finishReveal();seatAudio.play('revealed');}},reduceMotion()?700:520);}
  function startClickReveal(){finishReveal();if(!revealIds.length)return;selected=[];chosenStudent='';clickRevealActive=true;}
  function revealSeat(id:string){if(!clickRevealActive||!concealedIds.includes(id))return;clickRevealedIds=[...clickRevealedIds,id];seatAudio.play(clickRevealedIds.length===revealIds.length?'revealed':'choose');if(clickRevealedIds.length===revealIds.length)revealStepTimer=setTimeout(()=>{revealStepTimer=null;finishReveal();},reduceMotion()?100:620);}
  function stop(){worker?.terminate();worker=null;working=false;countdown=0;finishReveal();run++;}
  function reduceMotion(){return window.matchMedia('(prefers-reduced-motion: reduce)').matches;}
  function cancelRearrange(){stop();seatAudio.stop();if(curtainPreparing){curtainClosed=false;curtainPreparing=false;}}
  function sessionId(){const key=`tidy-seating-session-${classroom.id}`;let id=sessionStorage.getItem(key);if(!id){id=crypto.randomUUID();sessionStorage.setItem(key,id);}return id;}
  function scheduleFinalSave(next:Draft){if(finalSaveTimer)clearTimeout(finalSaveTimer);finalSaveTimer=null;if(!validAssignments(next,classroom.students,true))return;finalSaveTimer=setTimeout(()=>{finalSaveTimer=null;void persist({type:'saveCurrent',date:new Date().toLocaleDateString('sv-SE'),sessionId:sessionId()});},850);}
  function openCurtain(){if(curtainOpening||curtainPreparing)return;if(reduceMotion()){curtainClosed=false;seatAudio.play('revealed');return;}seatAudio.play('curtainLift');curtainOpening=true;if(curtainTimer)clearTimeout(curtainTimer);curtainTimer=setTimeout(()=>{curtainClosed=false;curtainOpening=false;curtainTimer=null;seatAudio.play('revealed');},1250);}
  function persist(action:any){const cl=clone(classroom);pending++;error='';const operationId=uid();queue=queue.then(async()=>{if(failed)throw Error('먼저 저장 문제를 해결해 주세요.');const s=await saveAction(cl,ownRevision,action,operationId);if(classroom?.id===cl.id){snapshot=s;doc=s.seating![cl.id];ownRevision=doc.revision;}status=action.type==='saveCurrent'?'현재 자리를 자동으로 기록했어요.':'저장됨';}).catch(e=>{failed=true;error=String(e);status='저장하지 못했어요';}).finally(()=>{pending--;if(!pending&&!failed)void refresh();});return queue;}
  function change(next:Draft,history=true,keepCandidates=false){if(frozen||failed||!draft)return;if(history){undo=[...undo.slice(-49),clone(draft)];redo=[];}draft=clone(next);draft.rosterRevision=classroom.revision;selected=selected.filter(id=>draft.layout.seats.some(s=>s.id===id));if(!keepCandidates){stop();candidates=[];candidateIndex=-1;}void persist({type:'saveDraft',draft:clone(draft)});scheduleFinalSave(draft);}
  // 드롭다운 맨 아래 "학급 추가"는 학급이 아니라 명령입니다. 학급 명단 창의 [학급 추가]를 대신 눌러 주고,
  // 선택 칸은 지금 학급으로 되돌립니다(학급 추가를 취소해도 자리 배치 화면이 그대로 남도록).
  const ADD_CLASS='__add-class__';
  function pickClass(e:Event&{currentTarget:HTMLSelectElement}){const value=e.currentTarget.value;if(value!==ADD_CLASS){void switchClass(value,false);return;}e.currentTarget.value=classroom?.id||'';void openRosterFor({action:'create-class'});}
  async function switchClass(id:string,tracking=false){await queue;if(failed)return;follow=tracking;pinned=id;localStorage.setItem('tidy-seating-binding',JSON.stringify({follow,pinned}));await context(id,follow);await refresh();}
  function stepUndo(back=true){const source=back?undo:redo;if(!source.length||pending)return;const next=source.at(-1);if(back){redo=[...redo,clone(draft)];undo=undo.slice(0,-1);}else{undo=[...undo,clone(draft)];redo=redo.slice(0,-1);}if(next)change(next,false);}
  function select(id:string,multiple=false){
    if(chosenStudent){const d=clone(draft);const displaced=d.assignments[id];if(displaced){error='이미 앉아 있는 학생이 있어요. 비어 있는 칸을 골라 주세요.';return;}d.assignments[id]=chosenStudent;if(violations(d).length){error='선생님 설정에서 배치 조건을 확인해 주세요.';return;}change(d);chosenStudent='';selected=[];return;}
    if(!selected.length){selected=[id];return;}if(selected[0]===id){selected=[];return;}swap(selected[0],id);selected=[];
  }
  function swap(from:string,to:string){const d=clone(draft),a=d.assignments[from],b=d.assignments[to];if(!a&&!b)return;if(a)d.assignments[to]=a;else delete d.assignments[to];if(b)d.assignments[from]=b;else delete d.assignments[from];if(violations(d).length||!d.layout.seats.find(s=>s.id===to)?.active){error='선생님 설정에서 배치 조건을 확인해 주세요.';return;}change(d);seatAudio.play('move');}
  function toggleLock(id:string){const d=clone(draft),student=d.assignments[id],existing=d.rules.find(r=>r.kind==='fixed'&&r.seatId===id);if(existing)d.rules=d.rules.filter(r=>r.id!==existing.id);else if(student){d.rules=d.rules.filter(r=>r.kind!=='fixed'||r.students[0]!==student);d.rules.push({id:uid(),kind:'fixed',students:[student],seatId:id});}else return;change(d);seatAudio.play(existing?'unlock':'lock');}
  function adjustGrid(axis:'columns'|'rows',delta:number){const next=resizeLayout(draft,axis,delta);if(!next){error='학생이나 지정 조건이 있는 자리까지는 줄일 수 없어요. 빈자리를 확인해 주세요.';return;}change(next);seatAudio.play(delta>0?'grow':'shrink');}
  function adjustZoom(delta:number){zoom=Math.max(.6,Math.min(2,Math.round((zoom+delta)*10)/10));}
  function openLayout(){shape=draft.layout.shape||'pairs';columns=draft.layout.columns||6;modal='layout';}
  function layout(){const d=clone(draft),people=d.layout.seats.map(s=>d.assignments[s.id]).filter(Boolean);d.layout=makeLayout(classroom.students.length,shape,Math.max(2,Math.min(12,Math.round(columns)||6)));d.assignments=Object.fromEntries(d.layout.seats.slice(0,people.length).map((s,i)=>[s.id,people[i]]));if(d.rules.some(r=>['fixed','zone'].includes(r.kind))&&!confirm('교실 모양을 바꾸면 사전 지정과 자리 자물쇠가 해제돼요. 계속할까요?'))return;d.rules=d.rules.filter(r=>!['fixed','zone'].includes(r.kind));change(d);zoom=1;modal='';}
  async function rearrange(){if(failed||working||countdown)return;effectMenuOpen=false;seatAudio.play('rearrange');await queue;if(failed||working||countdown)return;stop();working=true;const token=run;if(rearrangeMotion&&!reduceMotion()){await new Promise(resolve=>setTimeout(resolve,260));if(token!==run)return;for(const n of [3,2,1]){countdown=n;seatAudio.play('count',{step:3-n});await new Promise(resolve=>setTimeout(resolve,680));if(token!==run)return;}countdown=0;}else{await new Promise(resolve=>setTimeout(resolve,160));if(token!==run)return;}if(revealEffect==='curtain'){curtainClosed=true;curtainPreparing=true;seatAudio.play('curtainDrop');await new Promise(resolve=>setTimeout(resolve,reduceMotion()?0:700));if(token!==run)return;}await propose();}
  async function propose(only:string[]=[]){await queue;if(failed){working=false;curtainPreparing=false;curtainClosed=false;return;}stop();resultMessage='';const token=run;worker=new Worker(new URL('../../lib/seating/solver.worker.js',import.meta.url),{type:'module'});working=true;worker.onmessage=e=>{if(token!==run)return;working=false;worker?.terminate();worker=null;candidates=e.data.candidates||[];candidateIndex=-1;resultMessage=e.data.message;curtainPreparing=false;if(candidates.length)applyCandidate(0,true);else curtainClosed=false;};worker.onerror=()=>{stop();curtainPreparing=false;curtainClosed=false;error='배치를 계산하지 못했어요. 다시 시도해 주세요.';};worker.postMessage({runId:token,draft:clone(draft),students:clone(classroom.students),archives:clone(dailyArchives(doc.archives)),seed:crypto.getRandomValues(new Uint32Array(1))[0],budget:classroom.students.length>60?900:260,only});}
  function applyCandidate(index:number,initial=false){if(!candidates[index]||(!initial&&candidateIndex===index))return;const d=clone(draft);d.assignments=candidates[index].assignments;candidateIndex=index;change(d,true,true);curtainClosed=revealEffect==='curtain';if(revealEffect==='sequence')startSequence();else if(revealEffect==='click')startClickReveal();else if(revealEffect==='none')seatAudio.play(initial?'revealed':'choose');else if(!initial)seatAudio.play('choose');}
  async function showTeacher(){await queue;if(!failed){await context(classroom.id,follow);await openTool('seating-teacher');}}
  async function exportImage(){try{error='';status='이미지를 만들고 있어요…';if(await downloadPng(publicBoard(draft,classroom.students,classroom.name,new Date().toLocaleDateString('sv-SE')),{teacher,simple,numbersOnly,font:getComputedStyle(document.documentElement).getPropertyValue('--tk-font').split(',')[0].replaceAll('"','').trim()})){status='PNG를 저장했어요.';modal='';}else status='저장을 취소했어요.';}catch(e){error=String(e);}}
  async function close(){if(finalSaveTimer){clearTimeout(finalSaveTimer);finalSaveTimer=null;if(validAssignments(draft,classroom.students,true))await persist({type:'saveCurrent',date:new Date().toLocaleDateString('sv-SE'),sessionId:sessionId()});}await queue;if(failed)return;if(native)await getCurrentWindow().destroy();else window.close();}
  async function reload(){if(failed&&!confirm('저장하지 못한 변경을 버리고 저장된 내용을 불러올까요?'))return;failed=false;ownRevision=-1;error='';await refresh();}
  function saveRearrangeOptions(){seatAudio.setEnabled(soundEnabled);localStorage.setItem('tidy-seating-rearrange-options',JSON.stringify({motion:rearrangeMotion,effect:revealEffect,sound:soundEnabled}));}
  function selectRevealEffect(effect:RevealEffect){revealEffect=effect;effectMenuOpen=false;saveRearrangeOptions();}
  function closeGuide(){modal='';queueMicrotask(()=>helpButton?.focus());}
  function focusDialog(node:HTMLElement){queueMicrotask(()=>node.focus());}
  function trapDialog(e:KeyboardEvent){if(e.key!=='Tab')return;const dialog=e.currentTarget as HTMLElement;const controls=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]')).filter(el=>el.getClientRects().length>0);if(!controls.length)return;const first=controls[0],last=controls.at(-1)!;if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
  onMount(()=>{const offs:(()=>void)[]=[];void(async()=>{try{if(!teacherOnly){try{const saved=JSON.parse(localStorage.getItem('tidy-seating-binding')||'null');if(saved){follow=saved.follow;pinned=saved.pinned;}const options=JSON.parse(localStorage.getItem('tidy-seating-rearrange-options')||'null');if(options){rearrangeMotion=options.motion!==false;revealEffect=['none','curtain','sequence','click'].includes(options.effect)?options.effect:options.curtain===true?'curtain':'none';soundEnabled=options.sound!==false;seatAudio.setEnabled(soundEnabled);}}catch{}}
    offs.push(await subscribeRoster(()=>void refresh()));offs.push(await watchContext(()=>{if(teacherOnly)void refresh();}));await refresh();
    if(native){const win=getCurrentWindow();offs.push(await win.onCloseRequested(e=>{e.preventDefault();void close();}));offs.push(await listen('classroom-quit-request',async(event:any)=>{frozen=true;await queue;await invoke('noticeboard_quit_reply',{requestId:event.payload.requestId,allow:!failed});if(failed)frozen=false;}));offs.push(await listen('noticeboard-quit-cancel',()=>frozen=false));}
  }catch(e){error=String(e);ready=true;}})();const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{disposed=true;stop();seatAudio.dispose();if(finalSaveTimer)clearTimeout(finalSaveTimer);if(curtainTimer)clearTimeout(curtainTimer);offs.forEach(off=>off());window.removeEventListener('focus',focus);};});
</script>

<svelte:window onclick={e=>{if(effectMenuOpen&&e.target instanceof Element&&!e.target.closest('.seat-effect-picker'))effectMenuOpen=false;}} onkeydown={e=>{if(e.key==='Escape'){if(effectMenuOpen){effectMenuOpen=false;return;}if(modal){if(modal==='help')closeGuide();else modal='';return;}selected=[];chosenStudent='';cancelRearrange();}if(!modal&&(e.ctrlKey||e.metaKey)&&e.key==='z'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();stepUndo(!e.shiftKey);}}}/>
<div class="seating-app" class:teacher-window={teacherOnly} style:--seat-font={`${fontSize}px`} inert={frozen}>
  <header class="seating-titlebar" use:dragRegion><div class="seat-brand"><Armchair size={23}/><b>{teacherOnly?'선생님 설정':'자리 배치'}</b></div><span class="seat-save-status" role="status">{pending?'저장 중…':status||'학급 명단과 연결'}</span><div class="window-actions"><button title="창 크게" aria-label="창 크게" onclick={()=>native&&getCurrentWindow().toggleMaximize()}><Maximize2 size={18}/></button>{#if !teacherOnly}<button class="seat-guide-entry" bind:this={helpButton} title="자리 배치 가이드북" aria-label="자리 배치 가이드북 열기" onclick={()=>modal='help'}><CircleHelp size={20}/></button>{/if}<button aria-label="창 닫기" onclick={close}><X size={20}/></button></div></header>
  {#if error}<div class="seat-error" role="alert"><span>{error}</span>{#if failed}<button onclick={reload}>저장된 내용 다시 불러오기</button>{/if}<button aria-label="알림 닫기" onclick={()=>error=''}>×</button></div>{/if}
  {#if !ready}<div class="seat-empty-state"><Armchair size={44}/><h2>우리 교실을 준비하고 있어요</h2></div>
  {:else if !classroom.id}<div class="seat-empty-state"><BookOpen size={48}/><h1>우리 반 명단으로 시작해요</h1><p>학급을 한 번 등록하면 자리 배치에 바로 연결돼요.</p>{#if snapshot.classes.length}<select aria-label="사용할 학급" onchange={e=>switchClass(e.currentTarget.value,false)}><option value="">학급 고르기</option>{#each snapshot.classes as c}<option value={c.id}>{c.name}</option>{/each}</select>{/if}{#if !native && import.meta.env.DEV}<button onclick={async()=>{const {createDemo}=await import('../../lib/seating/demo.js');await createDemo();follow=true;await refresh();}}>가상 학급으로 체험하기</button>{/if}<button class="seat-primary" onclick={()=>openRosterFor({action:'create-class'})}>학급 명단 등록하기</button></div>
  {:else if teacherOnly}<TeacherPanel {draft} {classroom} document={doc} onchange={change} onaction={persist} busy={!!pending||failed}/>
  {:else}
    <div class="seat-classbar"><div><select class="class-picker" aria-label="배치할 학급" value={classroom.id} onchange={pickClass}>{#each snapshot.classes as c}<option value={c.id}>{c.name}</option>{/each}<option disabled>──────────</option><option value={ADD_CLASS}>＋ 학급 추가…</option></select><span>{classroom.students.length}명</span><button class="follow-class" class:active={follow} onclick={()=>switchClass(snapshot.defaultClassId||"",true)}>{follow?'기본 학급 따라가는 중':'기본 학급 따라가기'}</button></div><div class="seat-header-actions"><button class="seat-layout-button" onclick={openLayout}><LayoutGrid size={19}/>교실 모양</button><button class="seat-teacher-button" onclick={showTeacher}><Settings2 size={18}/> 선생님 설정</button></div></div>
    <div class="seat-zoom seat-toolbar" role="group" aria-label="자리 배치 도구">
      <div class="seat-view-tools seat-tool-group" role="group" aria-label="자리 편집">
        <span class="seat-tool-label" aria-hidden="true">편집</span>
        <div class="seat-tool-segment"><button disabled={!undo.length||!!pending} onclick={()=>stepUndo()} aria-label="되돌리기" title="되돌리기"><Undo2 size={17}/></button><button disabled={!redo.length||!!pending} onclick={()=>stepUndo(false)} aria-label="다시 하기" title="다시 하기"><Redo2 size={17}/></button></div>
        <span class="seat-drag-hint">{clickRevealActive?'실루엣을 누르면 한 명씩 공개돼요':sequenceActive?'학생 자리를 차례로 공개하고 있어요':'두 학생을 누르거나 끌어 바꿔요'}</span>
      </div>
      <div class="seat-fit-tools seat-tool-group" role="group" aria-label="화면 조절">
        <span class="seat-tool-label" aria-hidden="true">화면</span>
        <div class="seat-tool-segment"><button aria-label="축소" title="축소" disabled={zoom<=.6} onclick={()=>adjustZoom(-.1)}><Minus size={16}/></button><button class="seat-fit-button" onclick={()=>zoom=1} title="교실 크기에 맞추기">교실에 맞추기</button><button aria-label="확대" title="확대" disabled={zoom>=2} onclick={()=>adjustZoom(.1)}><Plus size={16}/></button></div>
        <button class="seat-simple-toggle" class:active={simple} aria-pressed={simple} onclick={()=>simple=!simple}>간단히 보기</button>
      </div>
      <div class="seat-perspective-tools seat-tool-group" role="group" aria-label="보는 기준">
        <span class="seat-tool-label" aria-hidden="true">시점</span>
        <div class="seat-view-switch" role="group" aria-label="자리 배치를 보는 기준"><button class="seat-view-student" class:active={!teacher} aria-pressed={!teacher} onclick={()=>teacher=false}>학생 기준</button><button class="seat-view-teacher" class:active={teacher} aria-pressed={teacher} onclick={()=>teacher=true}>교사 기준</button></div>
      </div>
    </div>
    <div class="seat-workspace">
      {#if shownBoard}<ClassroomScene board={shownBoard} {teacher} {selected} locked={revealInProgress?[]:lockedSeats} concealed={concealedIds} revealing={clickRevealedIds} onselect={select} onreveal={revealSeat} onswap={swap} onlock={toggleLock} onresize={adjustGrid} resizable lockable={!revealInProgress} disabled={failed||working||!!countdown||curtainClosed||revealInProgress} {zoom} {simple}/>{/if}
      {#if countdown}<div class="seat-countdown" role="status" aria-live="assertive"><div><small>새 자리 공개까지</small>{#key countdown}<strong>{countdown}</strong>{/key}</div></div>{/if}
      {#if curtainClosed}<div class="seat-curtain" class:opening={curtainOpening} role="status" aria-live="polite"><div class="seat-curtain-panel"><div class="seat-screen-rail"><i></i><span>TIDY CLASSROOM</span><i></i></div><div class="seat-screen-sheet">{#if curtainPreparing}<span class="seat-screen-kicker">자리 재배치 중</span><h2>새 자리를 준비하고 있어요</h2><p>잠시만 기다려 주세요.</p>{:else}<span class="seat-screen-kicker">자리 재배치 완료</span><h2>새 자리가 준비됐어요</h2><p>학생들이 화면에 집중하면 새 자리를 보여 주세요.</p><button class="seat-primary" disabled={curtainOpening} onclick={openCurtain}><Eye size={18}/>새 자리 보여 주기</button><small>선생님이 누르기 전까지 안전하게 가려져요.</small>{/if}</div><div class="seat-screen-handle"><i></i></div></div></div>{/if}
      {#if revealInProgress}<div class="seat-reveal-progress" role="group" aria-label={sequenceActive?'순차적 공개 진행 중':'1개씩 클릭 진행 중'}><div><small>{sequenceActive?'순차적 공개':'실루엣을 눌러 공개'}</small><b aria-live="polite">{sequenceActive?revealedCount:clickRevealedIds.length} / {revealIds.length}명 공개</b></div>{#if clickRevealActive}<button class="seat-reveal-next" disabled={!concealedIds.length} onclick={()=>revealSeat(concealedIds[0])}>다음 자리 공개</button>{/if}<button onclick={finishReveal}>한 번에 보기</button></div>{/if}
    </div>
    {#if waiting.length}<section class="seat-waiting"><b>아직 자리 없는 학생 <span>{waiting.length}</span></b><div>{#each waiting as p}<button class:active={chosenStudent===p.id} onclick={()=>{chosenStudent=chosenStudent===p.id?'':p.id;selected=[];}}>{p.number} {p.name}</button>{/each}</div></section>{/if}
    {#if resultMessage}<p class="seat-notice">배치를 찾지 못했어요. 선생님 설정에서 조건을 확인해 주세요.</p>{/if}
    <footer class="seat-footer seat-editor-footer"><div class="seat-rearrange-controls"><label class="seat-mini-toggle" title="켜면 3·2·1 뒤에 새 자리를 보여 줘요"><span>애니메이션<small>3·2·1</small></span><input type="checkbox" bind:checked={rearrangeMotion} onchange={saveRearrangeOptions}/><i></i></label><div class="seat-effect-picker"><button class="seat-effect-trigger" aria-expanded={effectMenuOpen} aria-controls="seat-effect-menu" disabled={working||!!countdown||curtainClosed||revealInProgress} onclick={()=>effectMenuOpen=!effectMenuOpen}><span><small>공개 효과</small><b>{revealEffect==='none'?'효과 없음':revealEffect==='curtain'?'가림막':revealEffect==='sequence'?'순차적 공개':'1개씩 클릭'}</b></span><ChevronUp size={17}/></button>{#if effectMenuOpen}<div id="seat-effect-menu" class="seat-effect-menu" role="group" aria-label="공개 효과 선택"><div class="seat-effect-menu-heading">새 자리를 보여 주는 방법</div><button class:active={revealEffect==='none'} aria-pressed={revealEffect==='none'} onclick={()=>selectRevealEffect('none')}><span class="seat-effect-option-icon">①</span><span><b>효과 없음</b><small>완성된 자리를 한 번에 보여줘요.</small></span><span class="seat-effect-check" aria-hidden="true">✓</span></button><button class:active={revealEffect==='curtain'} aria-pressed={revealEffect==='curtain'} onclick={()=>selectRevealEffect('curtain')}><span class="seat-effect-option-icon">②</span><span><b>가림막</b><small>선생님이 버튼을 눌러 열어요.</small></span><span class="seat-effect-check" aria-hidden="true">✓</span></button><button class:active={revealEffect==='sequence'} aria-pressed={revealEffect==='sequence'} onclick={()=>selectRevealEffect('sequence')}><span class="seat-effect-option-icon">③</span><span><b>순차적 공개</b><small>학생 자리가 자동으로 차례로 나타나요.</small></span><span class="seat-effect-check" aria-hidden="true">✓</span></button><button class:active={revealEffect==='click'} aria-pressed={revealEffect==='click'} onclick={()=>selectRevealEffect('click')}><span class="seat-effect-option-icon">④</span><span><b>1개씩 클릭</b><small>실루엣을 누를 때마다 한 명씩 공개해요.</small></span><span class="seat-effect-check" aria-hidden="true">✓</span></button></div>{/if}</div><label class="seat-mini-toggle" title="자리배치 조작 효과음 켜기 또는 끄기"><span>효과음<small>조작 소리</small></span><input type="checkbox" bind:checked={soundEnabled} onchange={saveRearrangeOptions}/><i></i></label><div class="seat-main-actions"><button class="seat-export-button" onclick={()=>modal='export'}><Download size={18}/>PNG 저장</button>{#if working||countdown||curtainPreparing}<button class="seat-rearrange-primary" onclick={cancelRearrange}>재배치 취소</button>{:else}<button class="seat-rearrange-primary" title="마지막 결과를 자동 저장해요" disabled={!!pending||failed||!classroom.students.length||curtainOpening||curtainClosed||revealInProgress} onclick={rearrange}>자리 재배치</button>{/if}</div></div></footer>
  {/if}
</div>
{#if modal}<div class="seat-modal-backdrop" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="seat-dialog-title" class="seat-dialog" class:seat-guide-dialog={modal==='help'} tabindex="-1" use:focusDialog onkeydown={trapDialog}><header class:seat-guide-header={modal==='help'}><h2 id="seat-dialog-title">{#if modal==='help'}<BookOpen size={24}/>자리 배치 가이드북{:else}{modal==='layout'?'우리 교실 모양':'PNG 저장'}{/if}</h2><button aria-label="닫기" onclick={()=>modal==='help'?closeGuide():modal=''}><X size={20}/></button></header>
  {#if modal==='help'}<SeatingGuide />
  {:else if modal==='layout'}<p>앉는 모양과 가로 자리 수를 정하면 반듯하게 맞춰 드려요.</p><div class="layout-options">{#each SHAPES as [key,label]}<button class:active={shape===key} onclick={()=>shape=key}><span class={`layout-mini mini-${key}`}>{#each Array(8) as _,i}<i></i>{/each}</span>{label}</button>{/each}</div><label>가로로 놓을 책상 수 <input type="number" min="2" max="12" bind:value={columns}/></label><button class="seat-primary full" onclick={layout}>이 모양으로 배치</button>
   {:else if modal==='export'}<p>현재 보는 배치를 학생 이름과 함께 저장해요. 선생님 조건은 포함하지 않습니다.</p><div class="seat-view-switch" role="group" aria-label="PNG를 저장할 때 보는 기준"><button class="seat-view-student" class:active={!teacher} aria-pressed={!teacher} onclick={()=>teacher=false}>학생 기준</button><button class="seat-view-teacher" class:active={teacher} aria-pressed={teacher} onclick={()=>teacher=true}>교사 기준</button></div><label class="seat-check"><input type="checkbox" bind:checked={numbersOnly}/>이름 없이 번호만</label><label class="seat-check"><input type="checkbox" bind:checked={simple}/>그림 없이 간단한 배치도</label><button class="seat-primary full" onclick={exportImage}><Download size={18}/>PNG 다운로드</button>
    {/if}
</div></div>{/if}
